### ISSUE TITLE
jsonschema dependency

### ISSUE THREAD

**Issue by bretttully** [jupyter/jupyter_events#58]
In [schema.py](https://github.com/jupyter/jupyter_events/blob/main/jupyter_events/schema.py#L7) you import `from jsonschema.protocols import Validator` for the purposes of adding a type hint. As far as I can see, this is the only reason why you need to depend on `jsonschema >=4`. Unfortunately, the community has not been speedy on adopting `jsonschema >=4` in many, many places (for instance [here](https://github.com/conda-forge/jupyter_events-feedstock/issues/5) and [here](https://github.com/kubeflow/pipelines/issues/8648)).

I was wondering if it makes sense to remove the type hint or at least have something like the following, and then drop the dependency for jsonschema back down to `3.x`?

```python
try:
    from jsonschema.protocols import Validator
except ImportError:
    from typing import Any
    Validator = Any
```

While not ideal, the way it is currently means that there is a lot of packages that cannot co-exist with jupyter in the conda ecosystem right now.

**Comment by kevin-bates** [comment]
Resolved via #59.
